name: "Bindgen"

on:
  workflow_call:
  workflow_dispatch:

jobs:

  bindgen-ffi-job:
    name: "Bindgen FFI"
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Windows, os: windows-latest, rid: win }
          - { name: macOS, os: macos-latest, rid: osx }
          - { name: Linux, os: ubuntu-latest, rid: linux }

    steps:
      - name: "Clone Git repository"
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: "Install c2ffi"
        shell: bash
        run: dotnet tool install --global bottlenoselabs.c2ffi.tool

      - name: "Read C code: Linux dependencies"
        if: runner.os == 'Linux'
        run: sudo apt-get install gcc-aarch64-linux-gnu

      - name: "Read C code: extract FFI ${{ matrix.platform.rid }}"
        shell: bash
        run: ./bindgen/bindgen-extract.sh

      - name: "Upload FFIs"
        uses: actions/upload-artifact@v4
        with:
          name: "ffi-${{ matrix.platform.rid }}"
          path: "./bindgen/ffi"

  bindgen-cross-platform-ffi-job:
    name: "Bindgen FFI cross-platform"
    needs: [bindgen-ffi-job]
    runs-on: ubuntu-latest

    steps:
      - name: "Clone Git repository"
        uses: actions/checkout@v4
        with:
          submodules: 'false'

      - name: "Download FFI (win)"
        uses: actions/download-artifact@v4
        with:
          name: "ffi-win"
          path: "./bindgen/ffi"

      - name: "Download FFI (osx)"
        uses: actions/download-artifact@v4
        with:
          name: "ffi-osx"
          path: "./bindgen/ffi"

      - name: "Download FFI (linux)"
        uses: actions/download-artifact@v4
        with:
          name: "ffi-linux"
          path: "./bindgen/ffi"

      - name: "Install c2ffi"
        shell: bash
        run: dotnet tool install --global bottlenoselabs.c2ffi.tool

      - name: "Generate cross-platform FFI"
        shell: bash
        run: ./bindgen/bindgen-merge.sh

      - name: "Upload cross-platform FFI"
        uses: actions/upload-artifact@v4
        with:
          name: "ffi-x"
          path: "./bindgen/ffi-x/cross-platform.json"

  bindgen-cs-job:
    name: "Bindgen C#"
    needs: [bindgen-cross-platform-ffi-job]
    runs-on: ubuntu-latest

    steps:
      - name: "Clone Git repository"
        uses: actions/checkout@v4
        with:
          submodules: 'false'

      - name: "Download C code cross-platform FFI"
        uses: actions/download-artifact@v4
        with:
          name: "ffi-x"
          path: "./bindgen/ffi-x"

      - name: "Install C2CS"
        shell: bash
        run: dotnet tool install -g bottlenoselabs.C2CS.Tool --version 2024.4.30-rc --add-source https://www.myget.org/F/bottlenoselabs/api/v3/index.json

      - name: "Generate C# code"
        shell: bash
        run: cd ./bindgen && ./bindgen-generate.sh

      - name: "Upload generated C# code"
        uses: actions/upload-artifact@v4
        with:
          name: "bindgen-cs"
          path: "./src/cs/production/SDL/Generated"
